version: "3.9"
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  api:
    build: ./apps/api
    ports:
      - "4000:4000"
    env_file:
      - ./apps/api/.env
    depends_on:
      - mongo
volumes:
  mongo: {}
